name: health_track_pro
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.0.0

  # Networking
  http: 1.3.0 

  # Secure Storage & Preferences
  flutter_secure_storage: ^8.0.0 
  shared_preferences: ^2.0.0 

  # Navigation
  go_router: ^6.0.0 
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
