name: health_track_pro
description: A healthcare management application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.1.1

  # State Management
  provider: ^6.0.5

  # Networking
  http: ^1.1.0
  

  # Preferences & Storage
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Navigation
  go_router: ^6.0.0

  # Utilities
  intl: ^0.18.1
  email_validator: ^2.1.17
  fluttertoast: ^8.2.12
  connectivity_plus: ^4.0.1

  # Features
  qr_flutter: ^4.1.0
  country_picker: ^2.0.19
  intl_phone_field: ^3.2.0

  # Charts & Visuals
  fl_chart: ^0.63.0

  # Notifications & Sharing
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  pdf: ^3.11.3
  printing: ^5.13.1
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
