name: health_track_pro
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.3.0

  # State Management
  provider: ^6.0.0

  # Networking
  http: ^1.3.0
  

  # Preferences & Storage
  shared_preferences: ^2.0.0
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Navigation
  go_router: ^6.0.0

  # Utilities
  intl: ^0.19.0
  email_validator: ^2.1.17
  fluttertoast: ^8.2.4
  connectivity_plus: ^4.0.1

  # Features
  qr_flutter: ^4.0.0
  country_picker: ^2.0.19
  intl_phone_field: ^3.2.0

  # Charts & Visuals
  fl_chart: ^0.70.2

  # Notifications & Sharing
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  pdf: ^3.11.3
  printing: ^5.13.1
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
